title: My Website
description: Personal website and blog
baseurl: ""
url: "https://klitersik.github.io"

# Plugins
plugins:
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"
